// NebenkostenRadar — Ratgeber-Artikel
// Diese Datei wird vom Rechtsmonitor (scripts/rechtsmonitor.mjs) automatisch erweitert.
// Neue Artikel werden am Array-Anfang eingefügt (neueste zuerst).
// Alte Artikel NIEMALS löschen — sie ranken bei Google weiter.

export const ARTIKEL = [
    {
      id: "widerspruch-nebenkostenabrechnung",
      titel: "Widerspruch Nebenkostenabrechnung 2026: Frist, Muster & Anleitung",
      teaser: "12 Monate Zeit, aber nur 30 Tage für die Nachzahlung — viele Mieter verwechseln diese Fristen. Was Sie jetzt wissen müssen.",
      datum: "Juni 2026",
      lesezeit: "6 Min.",
      bild: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80",
      bildAlt: "Schreibtisch mit Dokumenten und Stift",
      kategorie: "Mietrecht",
      keywords: ["Widerspruch Nebenkostenabrechnung", "Frist", "Muster", "§ 556 BGB"],
      inhalt: [
        { typ: "intro", text: "Sie haben Ihre Nebenkostenabrechnung erhalten und vermuten Fehler? Dann haben Sie als Mieter das Recht, innerhalb von 12 Monaten Widerspruch einzulegen. Doch Vorsicht: Die Zahlungsfrist für eine Nachzahlung beträgt nur 30 Tage — unabhängig vom Widerspruch. Wer das verwechselt, riskiert Verzugszinsen oder schlimmstenfalls die Kündigung." },
        { typ: "h2", text: "Die zwei entscheidenden Fristen — und warum viele Mieter sie verwechseln" },
        { typ: "text", text: "Das Mietrecht kennt zwei völlig unterschiedliche Fristen nach Erhalt der Nebenkostenabrechnung:" },
        { typ: "liste", items: [
          "30 Tage: Zahlungsfrist für eine Nachzahlung (§ 286 BGB). Diese Frist gilt unabhängig davon, ob Sie Widerspruch einlegen. Lösung: Zahlen Sie unter Vorbehalt — schreiben Sie auf die Überweisung: 'Zahlung unter Vorbehalt der Überprüfung'.",
          "12 Monate: Widerspruchsfrist gegen fehlerhafte Positionen (§ 556 Abs. 3 BGB). Die Frist beginnt mit dem Tag des Erhalts der Abrechnung.",
        ]},
        { typ: "hinweis", text: "Wichtig: Zahlung unter Vorbehalt schützt Sie. Auch wenn Sie die Nachzahlung leisten, können Sie innerhalb von 12 Monaten noch Widerspruch einlegen und zu viel gezahltes Geld zurückfordern." },
        { typ: "h2", text: "Wann lohnt sich ein Widerspruch?" },
        { typ: "text", text: "Ein Widerspruch ist sinnvoll wenn Ihre Abrechnung formelle oder inhaltliche Fehler enthält:" },
        { typ: "liste", items: [
          "Formelle Fehler (gravierend): Abrechnung fehlt ganz, wurde zu spät zugestellt (nach dem 31.12. des Folgejahres), oder enthält keinen nachvollziehbaren Verteilerschlüssel. Folge: Die gesamte Abrechnung ist unwirksam — Sie müssen keine Nachzahlung leisten.",
          "Inhaltliche Fehler: Nicht umlagefähige Posten (z.B. Kabelanschluss seit Juli 2024, Verwaltungskosten, Reparaturen), überhöhte Beträge über dem DMB-Richtwert, Verstoß gegen die Heizkostenverordnung.",
        ]},
        { typ: "h2", text: "Schritt-für-Schritt: So legen Sie wirksam Widerspruch ein" },
        { typ: "schritte", items: [
          "Abrechnung systematisch prüfen: Jeden Posten auf Umlagefähigkeit (§ 2 BetrKV) und Plausibilität (DMB-Betriebskostenspiegel) prüfen.",
          "Fehler konkret benennen: Pauschal 'die Abrechnung ist falsch' reicht nicht — benennen Sie jeden strittigen Posten mit Betrag und Begründung.",
          "Widerspruch schriftlich formulieren: Per Einschreiben mit Rückschein — nur so ist der Zugang beim Vermieter beweisbar.",
          "Belegeinsicht anfordern: Sie haben das Recht, alle Originalrechnungen einzusehen (§ 259 BGB). Verlangen Sie die Belege immer — auch wenn Sie zahlen.",
          "Frist im Blick behalten: Spätestens 12 Monate nach Erhalt der Abrechnung muss der Widerspruch beim Vermieter eingegangen sein.",
        ]},
        { typ: "h2", text: "Was gehört in den Widerspruchsbrief?" },
        { typ: "text", text: "Ein wirksamer Widerspruch muss folgende Elemente enthalten:" },
        { typ: "liste", items: [
          "Ihre vollständige Adresse und die des Vermieters",
          "Klarer Betreff: 'Widerspruch zur Betriebskostenabrechnung [Jahr]'",
          "Konkrete Benennung der beanstandeten Positionen mit Betrag",
          "Rechtsgrundlage (z.B. '§ 2 BetrKV — nicht umlagefähig')",
          "Aufforderung zur Belegeinsicht (§ 259 BGB)",
          "Vorbehalt für weitere Einwände nach Belegeinsicht",
          "Bitte um schriftliche Stellungnahme",
        ]},
        { typ: "cta", text: "NebenkostenRadar erstellt den Widerspruchsbrief automatisch — mit allen Rechtsgrundlagen, auf Basis Ihrer konkreten Abrechnung." },
        { typ: "h2", text: "Häufige Fehler beim Widerspruch — und wie Sie sie vermeiden" },
        { typ: "liste", items: [
          "Nur mündlich widersprechen: Gilt rechtlich nicht — immer schriftlich.",
          "Zu pauschal formulieren: 'Die Abrechnung stimmt nicht' reicht nicht — konkrete Positionen nennen.",
          "Frist verpassen: Ab dem 13. Monat nach Erhalt sind Einwände in der Regel ausgeschlossen.",
          "Nicht unter Vorbehalt zahlen: Wer die Nachzahlung ohne Vorbehalt zahlt, erschwert eine spätere Rückforderung.",
        ]},
      ],
    },
    {
      id: "kabelanschluss-nicht-umlagefaehig",
      titel: "Kabelanschluss in Nebenkosten: Seit Juli 2024 nicht mehr umlagefähig",
      teaser: "Vermieter dürfen Kabelgebühren seit dem 01.07.2024 nicht mehr auf Mieter umlegen. Was das bedeutet und wie Sie zu viel gezahltes Geld zurückbekommen.",
      datum: "Juni 2026",
      lesezeit: "4 Min.",
      bild: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
      bildAlt: "Fernseher und Kabel",
      kategorie: "Rechtsänderungen",
      keywords: ["Kabelanschluss Nebenkosten", "nicht umlagefähig 2024", "§ 2 TKG"],
      inhalt: [
        { typ: "intro", text: "Seit dem 1. Juli 2024 dürfen Vermieter die Kosten für einen Kabelanschluss nicht mehr als Betriebskosten auf Mieter umlegen. Das Telekommunikationsgesetz (TKG) schreibt dies klar vor — trotzdem findet sich der Posten noch in vielen Abrechnungen." },
        { typ: "h2", text: "Was hat sich geändert?" },
        { typ: "text", text: "Bis Juni 2024 war es Vermietern erlaubt, Kosten für einen Sammelkabelanschluss (§ 2 Nr. 15b BetrKV a.F.) auf die Mieter umzulegen — das sogenannte 'Nebenkostenprivileg'. Durch das Telekommunikationsmodernisierungsgesetz (TKMoG) wurde dieses Privileg abgeschafft." },
        { typ: "hinweis", text: "Ab dem 01.07.2024 gilt: Kabelanschlusskosten sind keine umlagefähigen Betriebskosten mehr. Jeder Betrag unter diesem Posten in einer Abrechnung für Zeiträume ab Juli 2024 kann vollständig zurückgefordert werden." },
        { typ: "h2", text: "Welche Abrechnungen sind betroffen?" },
        { typ: "liste", items: [
          "Abrechnungen für das gesamte Jahr 2025 und später: Kabelkosten komplett nicht umlagefähig.",
          "Abrechnungen für 2024 (gemischter Zeitraum): Nur der Anteil ab Juli 2024 ist nicht umlagefähig — also 6/12 des Jahresbetrags.",
          "Abrechnungen für 2023 und früher: Das alte Recht gilt — Kabelkosten waren umlagefähig.",
        ]},
        { typ: "cta", text: "NebenkostenRadar erkennt Kabelanschlusskosten automatisch und weist sie als nicht umlagefähig aus — mit der korrekten Rechtsgrundlage für Ihren Widerspruch." },
      ],
    },
    {
      id: "betriebskostenspiegel-2024",
      titel: "DMB Betriebskostenspiegel 2024: Was ist normal?",
      teaser: "Der Deutsche Mieterbund veröffentlicht jährlich Durchschnittswerte für alle Nebenkostenarten. Hier erfahren Sie, was für Ihre Wohnungsgröße normal ist — und wann Ihre Abrechnung zu teuer ist.",
      datum: "Juni 2026",
      lesezeit: "5 Min.",
      bild: "https://images.unsplash.com/photo-1460472178825-e5240623afd5?w=800&q=80",
      bildAlt: "Wohngebäude in Deutschland",
      kategorie: "Richtwerte",
      keywords: ["Betriebskostenspiegel 2024", "DMB Richtwerte", "Nebenkosten Durchschnitt"],
      inhalt: [
        { typ: "intro", text: "Der Deutsche Mieterbund (DMB) veröffentlicht jährlich den Betriebskostenspiegel — eine Auswertung realer Nebenkostenabrechnungen in Deutschland. Er zeigt Durchschnittswerte und Höchstwerte für alle umlagefähigen Kostenarten pro Quadratmeter und Monat." },
        { typ: "h2", text: "Die wichtigsten Richtwerte 2024 im Überblick" },
        { typ: "tabelle", zeilen: [
          ["Kostenart", "Durchschnitt €/m²/Monat", "Jahresbetrag für 75 m²"],
          ["Heizung + Warmwasser", "1,32 €", "1.188 €"],
          ["Heizung + Warmwasser (Maximum)", "2,18 €", "1.962 €"],
          ["Wasser + Abwasser", "0,26 €", "234 €"],
          ["Grundsteuer", "0,21 €", "189 €"],
          ["Müllbeseitigung", "0,20 €", "180 €"],
          ["Hausmeister", "0,30 €", "270 €"],
          ["Versicherungen", "0,28 €", "252 €"],
          ["Aufzug", "0,18 €", "162 €"],
          ["Gartenpflege", "0,11 €", "99 €"],
          ["Allgemeinstrom", "0,08 €", "72 €"],
          ["Gesamt Durchschnitt", "2,67 €", "2.403 €"],
        ]},
        { typ: "hinweis", text: "Liegt Ihre Abrechnung mehr als 30% über dem Durchschnitt, ist eine Prüfung dringend empfohlen. NebenkostenRadar vergleicht automatisch jeden Posten mit diesen Richtwerten." },
        { typ: "h2", text: "Wie nutze ich die Richtwerte?" },
        { typ: "text", text: "Multiplizieren Sie den €/m²/Monat-Wert mit Ihrer Wohnfläche und mit 12 — das ergibt den erwarteten Jahresbetrag für Ihre Wohnung. Liegt ein Posten in Ihrer Abrechnung mehr als 30-40% darüber, ist das ein klarer Hinweis auf eine überhöhte Abrechnung." },
        { typ: "cta", text: "NebenkostenRadar macht diesen Vergleich automatisch für jeden Posten Ihrer Abrechnung — und zeigt Ihnen die Abweichung in Prozent." },
      ],
    },
  ];
